services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./secrets:/app/secrets
    restart: unless-stopped
